### ISSUE TITLE
[2.4.2] Object queries not working as described

### ISSUE THREAD

**Issue by lsparlin** [baweaver/qo#11]
`version = ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]`

using Person object 
```
class Person
  attr_reader :name, :age
  def initialize(n, a)
    @name = n
    @age = a
  end
end
```

qo query `youth = people.select(&Qo[age: 0..18])` gives the following error 
```
matcher.rb:149:in `block in hash_against_object_matcher': 
  wrong number of arguments (given 1, expected 2) (ArgumentError)
```

**Comment by baweaver** [comment]
```
➜  q git:(master) pry
[1] pry(main)> edit
=> [{:name=>"Jon", :age=>29}, {:name=>"Jane", :age=>27}, {:name=>"Joe", :age=>5}, {:name=>"Lucy", :age=>2}]
[2] pry(main)> people
=> [#<Person:0x007fa6800ada88 @age=29, @name="Jon">, #<Person:0x007fa6800adf88 @age=27, @name="Jane">, #<Person:0x007fa6800aff40 @age=5, @name="Joe">, #<Person:0x007fa6800aff18 @age=2, @name="Lucy">]
[3] pry(main)> youth = people.select(&Qo[age: 0..18])
=> [#<Person:0x007fa6800aff40 @age=5, @name="Joe">, #<Person:0x007fa6800aff18 @age=2, @name="Lucy">]
[4] pry(main)> youth_h = ppl_hashes.select(&Qo[age: 0..18])
=> [{:name=>"Joe", :age=>5}, {:name=>"Lucy", :age=>2}]
[5] pry(main)> exit
➜  q git:(master) ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]
```

Interesting. I wonder if 2.4.x did something then. Switching to that.

**Comment by baweaver** [comment]
Yep, crashing on 2.4.2. Interesting, it might be something to do with how varargs and kwargs are interpreted, digging in.

**Action Items**

* Create CI task to catch against different common Ruby versions

**Comment by baweaver** [comment]
For whatever reason in 2.4.2 it'll not deconstruct hash arguments and try and pass them as a single array. Trying on 2.4.4 to see if that still happens

**Comment by baweaver** [comment]
Also appears broken in 2.5.1. Looks like something changed to make it not respect block arity (hash being 2, this is probably passing [:name, :*] as a single argument)

**Comment by baweaver** [comment]
Isolated issue to being somewhere after 2.4.x in that `lambda` style functions won't deconstruct their arguments anymore. I assume this was done for some type of performance gain, but still trying to figure out how that works.

**Comment by baweaver** [comment]
Well, short version I think we broke parts of Ruby XD

Will probably have to get to this later today as it'll take some debugging to trace through, and hopefully a bug report is in core for it already. If not I'll make one of those as well.

**Comment by baweaver** [comment]
https://stackoverflow.com/questions/14992471/how-do-i-pass-a-lambda-to-hash-each

Yep. I have a tendency to use lambdas without the `()` destructuring which apparently got broken between 2.3 and 2.4. Switched to using Proc and most of it is working except for a few test failures from some magic I was doing in the same vein.

**Comment by baweaver** [comment]
Got it fixed in https://github.com/baweaver/qo/commit/f7c17eb500e5b9d057360cfe1314d99dc21b0865

Pesky, that. Honestly I think it's a bug in Ruby itself so I'll likely upstream that to core.

**Comment by baweaver** [comment]
Nope, Nobu already rocked a change - https://bugs.ruby-lang.org/issues/14639

Well, Procs for now then
