### ISSUE TITLE
Allow both positional and named arguments in the same query object

### ISSUE THREAD

**Issue by bfoz** [baweaver/qo#19]
AFAICT, it isn't currently possible to check that a target object is of the correct type as well as having a property with a particular value.

```ruby
# This is an example given in the README
Qo[Integer, 15..25] === 20

# But, this doesn't appear to work
MyKlass = Struct.new(:foo)
Qo[MyKlass, foo: 42] === MyKlass.new(42)
```

**Comment by baweaver** [comment]
It's done intentionally.

It _could_ be done, but it would also be a lot slower than using one or the other.

https://github.com/baweaver/qo/blob/master/lib/qo/public_api.rb#L129-L140

This is the relevant code area. The matchers fork based on whether a hash or an array type argument was provided. This was done for speed reasons, but it could be tweaked to compose the two matchers if both were provided.

A rewrite may look something like this:

```ruby
private def create_matcher(type, array_matchers, keyword_matchers)
  array_empty, hash_empty = array_matchers.empty?, keyword_matchers.empty?

  raise Qo::NoMatchersProvided if array_empty && hash_empty

  if !(array_empty || hash_empty)
    array_matcher = Qo::Matchers::ArrayMatcher.new(type, *array_matchers)
    hash_matcher  = Qo::Matchers::HashMatcher.new(type, **keyword_matchers)

    proc { |target| array_matcher.call(target) && hash_matcher.call(target) }
  elsif hash_empty
    Qo::Matchers::ArrayMatcher.new(type, *array_matchers)
  else
    Qo::Matchers::HashMatcher.new(type, **keyword_matchers)
  end
end
```

..but that would rely on it being only an `and` matcher. It could be abstracted even further to accommodate the others.

Admittedly I'm not totally sold on the idea. Do you have some more example usecases in mind?

**Comment by baweaver** [comment]
More over it'd just take me some time to think of how to pull it off without slowing things down too much. Let me think it over and see what I come up with. I know I can make it work, I just want it to work well and not slow it down too much.

**Comment by bfoz** [comment]
Sounds good. In case you're curious, here's is a simplified version of what I'm using in the meantime. It seems to work well enough, at least for what I'm doing. YMMV.

```ruby
class Matcher
    attr_reader :conditions

    def initialize(*args)
	@conditions = args
    end

    def ===(other)
	return true if self.conditions.empty?

	self.conditions.all? do |matcher|
	    if Hash === matcher
		matcher.empty? or matcher.all? do |k,v|
		    v === other.public_send(*k)
		end
	    else
		matcher === other
	    end
	end
    end
end
```

**Comment by baweaver** [comment]
Completed as of last update.
